### PR TITLE
add payment requirements in offer response

### PR DESCRIPTION
**Pull request by EarvinKayonga**
Hello @ivanvanderbyl,

Thanks for open sourcing this library.
This PR add `payment_requirements` to the Offer struct. 

image

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
Hi @EarvinKayonga thanks for the second contribution, much appreciated. Would you mind adding another test for this?

**Comment by EarvinKayonga** [comment]
@ivanvanderbyl, Just added some checks in the deserialization test.
Is that okay for u?

**Comment by ivanvanderbyl** [comment]
@EarvinKayonga yes, that would be great, just so that we have coverage to ensure future changes don't regress. See the existing tests for how to set this up.

**Review by ivanvanderbyl — APPROVED** [review]

**Comment by EarvinKayonga** [comment]
top

**Pull request merged**
